spring:
  cloud:
    config:
      discovery:
        enabled: true
        service-id: config-server
    loadbalancer:
      retry:
        enabled: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus