server:
  port: 8080

spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://mysql-db:3306/order_db
    username: root
    password: securepassword
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 10
      connection-timeout: 3000

zeebe:
  client:
    broker.gateway-address: zeebe-broker:26500
    security.plaintext: true