server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/korearun5/order-management-config.git
          search-paths: '{application}'
          clone-on-start: true
          force-pull: true
          default-label: main
          timeout: 10

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus
  metrics:
    tags:
      application: ${spring.application.name}