server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/korearun5/order-management-config.git
          default-label: main
          basedir: ./config-cache
          force-pull: true
          clone-on-start: true
          search-paths: '{application}'
          timeout: 30
          delete-untracked-branches: true

management:
  endpoints:
    web:
      exposure:
        include: health,info,refresh,prometheus

logging:
  level:
    root: INFO
    org.springframework.cloud.config.server: DEBUG
    org.springframework.cloud.config.server.environment: TRACE