server:
  port: 8888


spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/korearun5/config-repo
          username: korearun5
          password: ${GIT_TOKEN}
          ignore-local-ssh-settings: true
          private-key: |
            -----BEGIN RSA PRIVATE KEY-----
            MIIEpAIBAAKCAQEAszmC...
            ... (your private key contents) ...
            -----END RSA PRIVATE KEY-----
          skipSslValidation: false
          # (If using a private repo, you can set credentials or a token here)
          clone-on-start: true
          default-label: main

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
